# Generated by Django 4.2.5 on 2023-10-02 18:07

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload_file',
            field=models.FileField(default=None, upload_to='files', validators=[file.models.files.valid_file_extension]),
        ),
    ]
