# Generated by Django 4.2.5 on 2023-10-03 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_downloadtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtoken',
            name='file',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='file.files'),
        ),
    ]
