# Generated by Django 4.2.5 on 2023-10-01 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_files_options_files_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
