# Generated by Django 4.2.5 on 2023-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_downloadtoken_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtoken',
            name='assignment_id',
            field=models.IntegerField(default=800615),
        ),
    ]
