# Generated by Django 4.2.5 on 2023-10-02 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_alter_files_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='upload_file',
            field=models.FileField(default=None, max_length=250, upload_to='files', validators=[file.models.files.valid_file_extension]),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
