# Generated by Django 4.2.5 on 2023-10-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_downloadtoken_assignment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadtoken',
            name='token',
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='assignment_id',
            field=models.IntegerField(default=805759),
        ),
    ]
